name: PolyX
version: ${project.version}
main: eu.okaeri.polyx.bukkit.PolyXPlugin
description: 'Enterprise Grade Minecraft Scripting Adapter'
author: 'Dawid Sawicki <dawid@okaeri.eu>'
api-version: 1.13
